### ISSUE TITLE
Cannot login on firefox on debian

### ISSUE THREAD

**Issue by cooligus** [BaderBC/contexto-transletto#6]
![image](https://github.com/BaderBC/contexto-transletto/assets/67282004/99eede9f-3edc-497a-81dc-46f016cd0820)

No idea what causes the problem

**Comment by BaderBC** [comment]
How can I reproduce this bug?

**Comment by cooligus** [comment]
Click the `login with Google` button

**Comment by BaderBC** [comment]
btw I would be glad to see info about browser and extension version in your futute issues.

**Comment by BaderBC** [comment]
Resolved in f8ef72076fb6335820d672dfc82bd1949ef2df76
