### ISSUE TITLE
Gemini highlights wrong word 

### ISSUE THREAD

**Issue by cooligus** [BaderBC/contexto-transletto#8]
![image](https://github.com/BaderBC/contexto-transletto/assets/67282004/1b8893e9-b114-4ba3-84ed-7c17a4ab31d2)
As you can see in the screenshot above, wrong word has been highlighted

**Comment by BaderBC** [comment]
Your issue is directly related to #1

**Comment by BaderBC** [comment]
I decided to close this issue as I believe this is duplicate

**Comment by cooligus** [comment]
I believe it should be labelled as completed
